import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Logo from "./components/Logo";
import Menu from "./components/Menu/Menu";
import Navbar from "./components/Navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-screen flex bg-white">
        {/* LEFT SIDE */}
        <div className="w-[14%] md:w-[10%] lg:w-[14%] xl:w-[14%] p-4 bg-white">
          <Logo />
          <Menu />
        </div>

        {/* RIGHT SIDE */}
        <div className="w-[86%] md:w-[90%] lg:w-[86%] xl:w-[86%] overflow-scroll bg-gray-100">
          <Navbar />
          {children}
        </div>
        </div>
      </body>
    </html>
  );
}
